added snapping feature

diff --git a/usr/bin/lite-upgrade-series3 b/usr/bin/lite-upgrade-series3
--- a/usr/bin/lite-upgrade-series3
+++ b/usr/bin/lite-upgrade-series3
@@ -128,6 +128,20 @@ zenity --progress --percentage="$PERCENTAGE"  --title="Adding Execute bash scrip
 unset UPDATER
 }
 
+# Window snapping & tiling
+WINSNAP() {
+UPDATER=$( xfconf-query -c xfwm4 -p /general/tile_on_move -s true && xfconf-query -c xfwm4 -p /general/snap_resist -s true && xfconf-query -c xfwm4 -p /general/wrap_windows -s false && sleep 2 |
+zenity --progress --percentage=20  --title="Setting Window snapping feature..." \
+--width=600 --auto-close)
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text='There was an error while setting\nthe Window snapping feature'
+             fi
+unset UPDATER
+}
+
 # Modify terminal theme, file is: /home/$USER/.config/lxterminal/lxterminal.conf
 TERMTHEME() {
     echo "#Updating to new Terminal theme..."
@@ -274,6 +288,7 @@ case "$arch" in
     ARRAYA+=('ADDCONKY')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
     ARRAYA+=('HTOPTHEME')
@@ -284,6 +299,7 @@ case "$arch" in
     ARRAYA+=('ADDCONKY')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
     ARRAYA+=('HTOPTHEME')
@@ -313,6 +329,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER32')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('WINSNAP')
     ARRAYA+=('LITEWELCOME')
     ;;
     amd64)
@@ -320,6 +337,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER32')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('WINSNAP')
     ARRAYA+=('LITEWELCOME')
     ;;
 esac
