set new Default Notification theme

diff --git a/usr/bin/lite-upgrade-series3 b/usr/bin/lite-upgrade-series3
--- a/usr/bin/lite-upgrade-series3
+++ b/usr/bin/lite-upgrade-series3
@@ -131,6 +131,22 @@ zenity --progress --percentage="$PERCENTAGE"  --title="Adding Execute bash scrip
 unset UPDATER
 }
 
+# Change Notification theme
+NOTIFYCH() {
+    echo "#Updating to new Notification theme..."
+        cp /home/$USER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml /home/$USER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml.backup
+        sed -i '5d' /home/$USER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
+        sed -i '5i\ \ <property name="theme" type="string" value="Default"/>' /home/$USER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
+
+        sleep 2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nChanging the Notification theme!"
+                        fi
+}
+
 # Window snapping & tiling
 WINSNAP() {
 UPDATER=$( xfconf-query -c xfwm4 -p /general/tile_on_move -s true && xfconf-query -c xfwm4 -p /general/snap_resist -s true && xfconf-query -c xfwm4 -p /general/wrap_windows -s false && sleep 2 |
@@ -282,6 +298,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER30')
     ARRAYA+=('ADDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('NOTIFYCH')
     ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
@@ -292,6 +309,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER30')
     ARRAYA+=('ADDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('NOTIFYCH')
     ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
@@ -322,6 +340,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER32')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('NOTIFYCH')
     ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
@@ -331,6 +350,7 @@ case "$arch" in
     ARRAYA+=('BUPHOMEUSER32')
     ARRAYA+=('UPDCONKY')
     ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('NOTIFYCH')
     ARRAYA+=('WINSNAP')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
diff --git a/usr/bin/lite-upgrade-system-series3 b/usr/bin/lite-upgrade-system-series3
--- a/usr/bin/lite-upgrade-system-series3
+++ b/usr/bin/lite-upgrade-system-series3
@@ -59,6 +59,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('NOTIFYCHSKEL')
     ARRAYC+=('HTOPSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('GETCONKY')
@@ -73,6 +74,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('NOTIFYCHSKEL')
     ARRAYC+=('HTOPSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('GETCONKY')
@@ -108,6 +110,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('NOTIFYCHSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('UPDCONKSKEL')
     ;;
@@ -120,6 +123,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('NOTIFYCHSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('UPDCONKSKEL')
     ;;
@@ -252,6 +256,22 @@ zenity --progress --no-cancel --percentage="$PERCENTAGE"  --title="Updating boot
                 zenity --info --title="Lite Upgrade" --text="Error:\n${line}"
             fi    
 unset UPDATER
+}
+
+# Change Notification theme
+NOTIFYCHSKEL() {
+    echo "#Updating to new Notification theme..."
+        cp /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml.backup
+        sed -i '5d' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
+        sed -i '5i\ \ <property name="theme" type="string" value="Default"/>' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml
+
+        sleep 2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nChanging the Notification theme!"
+                        fi
 }
 
 # Change to new HTOP theme, file is: /etc/skel/.config/htop/htoprc
