start of code for 3.4 upgrade

diff --git a/usr/bin/lite-upgrade-series3 b/usr/bin/lite-upgrade-series3
--- a/usr/bin/lite-upgrade-series3
+++ b/usr/bin/lite-upgrade-series3
@@ -12,59 +12,127 @@
 export LANG=C
 
 # Linux Lite default dialog icon
-ic=/usr/share/icons/zenity-llcc.png
-run_icon=/usr/share/icons/Faenza/actions/32/system-run.png
+ic="/usr/share/icons/zenity-llcc.png"
 
 # Set functions for non-root execution
 # The ones that need root go to the other file: lite-upgrade-system-series3
-MKDIRBUPS() {
-    echo "#• Creating back up directories..."
+
+# Create back up directories for Linux Lite 3.0
+MKDIRBUPS30() {
+    echo "#Creating back up directories..."
     sleep 2
-    mkdir -p /home/$USER/.llupgradebackup/3.0
-        if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-            echo "#Error"
-            sleep 1
-            zenity --error --width="320" --title="  Error" \
-                   --text="\nAn error occurred while creating back up directories! \n\nUpgrade canceled."
-            exit 1
-        fi
+        mkdir -p /home/$USER/.llupgradebackup/3.0
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nCreating back up directories!\nUpgrade canceled."
+                    exit 1
+                        fi
 }
 
 # Copy all original files from /home/user and /etc/skel to their respective backup folders and versions
-# Backup /home/$USER/ first
-BUPHOMEUSER() {
-    echo "#• Backing up select home files..."
+
+# Backup /home/$USER/ select config files on Linux Lite 3.0
+BUPHOMEUSER30() {
+    echo "#Backing up select home files..."
 	chmod 755 /home/$USER/.config/htop/
 	chmod 755 /home/$USER/.config/lxterminal/
-    cp /home/$USER/.config/lxterminal/lxterminal.conf /home/$USER/.llupgradebackup/3.0
+        cp /home/$USER/.config/lxterminal/lxterminal.conf /home/$USER/.llupgradebackup/3.0
+        sleep 2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nBacking up select home files!"
+                        fi
+}
+
+# Create back up directories for Linux Lite 3.2
+MKDIRBUPS32() {
+    echo "#Creating back up directories..."
     sleep 2
-        if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-            echo "#Error"
-            sleep 1
-            zenity --error --width="320" --title="  Error" \
-                   --text="\nAn error occurred while backing up select home files!"
-        fi
+        mkdir -p /home/$USER/.llupgradebackup/3.2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nCreating back up directories!\nUpgrade canceled."
+                    exit 1
+                        fi
+}
+
+# Copy all original files from /home/user and /etc/skel to their respective backup folders and versions
+
+# Backup /home/$USER/ select config files on Linux Lite 3.2
+BUPHOMEUSER32() {
+    echo "#Backing up select home files..."
+	chmod 755 /home/$USER/.config/htop/
+	chmod 755 /home/$USER/.config/lxterminal/
+        cp /home/$USER/.config/htop/htoprc /home/$USER/.llupgradebackup/3.2
+        cp /home/$USER/.config/lxterminal/lxterminal.conf /home/$USER/.llupgradebackup/3.2
+        cp /home/$USER/.conky/widget /home/$USER/.llupgradebackup/3.2
+        sleep 2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nBacking up select home files!"
+                        fi
 }
 
 # Add Lite Desktop Widget
 ADDCONKY() {
-    echo "#• Adding Lite Desktop Widget..."
-    UPDATER=$( stdbuf -oL /bin/bash \-c '(cd ~/ && wget http://repo.linuxliteos.com/upgrade/3.0-3.2/liteconkywidget.tar.gz && tar xvzf liteconkywidget.tar.gz && rm liteconkywidget.tar.gz && sleep 2 )' 2>&1 |
-    stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-    zenity --progress --width="340" --window-icon="$run_icon" --no-cancel --percentage="$PERCENTAGE" --title="Adding Lite Desktop Widget..." --auto-close )
-        if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-            echo "#Error"
-            sleep 1
-            zenity --error --width="220" --title="  Error" \
-                   --text="\nAn error occurred while adding the Lite Desktop Widget!"
-        fi
+UPDATER=$( stdbuf -oL /bin/bash \-c '(cd ~/ && wget http://repo.linuxliteos.com/upgrade/3.0-3.2/liteconkywidget.tar.gz && tar xvzf liteconkywidget.tar.gz && rm liteconkywidget.tar.gz && sleep 2 )' 2>&1 |
+stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
+zenity --progress --percentage="$PERCENTAGE"  --title="Adding Lite Desktop Widget..." \
+--width=600 --auto-close )
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text='There was an error while adding\nthe Lite Desktop Widget!'
+             fi
+unset UPDATER
+}
+
+# Improvements to the Lite Desktop Widget
+UPDCONKY() {
+UPDATER=$( stdbuf -oL /bin/bash \-c '(sed -i "s/Logged in as.*/${color}Logged in as:   \${alignr}\${color}\$USER"/g ~/.conky/widget && sleep 2 )' 2>&1 |
+#UPDATER=$( stdbuf -oL /bin/bash \-c '(sudo sed -i "s/DISTRIB_DESCRIPTION=.*/DISTRIB_DESCRIPTION=\"Linux Lite 3.4\"/g" /etc/lsb-release && echo "Linux Lite 3.4" |
+#UPDATER=$( stdbuf -oL /bin/bash \-c '(cd ~/ && sed -i '/Logged in as.*/c\${color}Logged in as:   ${alignr}${color}$USER' ~/.conky/widget && sleep 2 )' 2>&1 |
+stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
+zenity --progress --percentage="$PERCENTAGE"  --title="Updating the Lite Desktop Widget..." \
+--width=600 --auto-close )
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text='There was an error while updating\nthe Lite Desktop Widget!'
+             fi
+unset UPDATER
+}
+
+# Execute bash scripts
+EXEBASHSCR() {
+UPDATER=$( stdbuf -oL /bin/bash \-c '(xfconf-query --channel thunar --property /misc-exec-shell-scripts-by-default --create --type bool --set true && sleep 2 )' 2>&1 |
+stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
+zenity --progress --percentage="$PERCENTAGE"  --title="Adding Execute bash scripts feature..." \
+--width=600 --auto-close )
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text='There was an error while adding the\nExecute bash scripts feature!'
+             fi
 unset UPDATER
 }
 
 # Modify terminal theme, file is: /home/$USER/.config/lxterminal/lxterminal.conf
 TERMTHEME() {
-    echo "#• Updating to new Terminal theme..."
+    echo "#Updating to new Terminal theme..."
         mv /home/$USER/.config/lxterminal/lxterminal.conf /home/$USER/.config/lxterminal/lxterminal.conf.backup
+        mv /etc/skel/.config/lxterminal/lxterminal.conf /etc/skel/.config/lxterminal/lxterminal.conf.backup
         touch /home/$USER/.config/lxterminal/lxterminal.conf
         echo "[general]" >> /home/$USER/.config/lxterminal/lxterminal.conf
         echo "fontname=Monospace 10" >> /home/$USER/.config/lxterminal/lxterminal.conf
@@ -83,37 +151,34 @@ TERMTHEME() {
         echo "hideclosebutton=false" >> /home/$USER/.config/lxterminal/lxterminal.conf
         echo "disablef10=true" >> /home/$USER/.config/lxterminal/lxterminal.conf
         echo "disablealt=false" >> /home/$USER/.config/lxterminal/lxterminal.conf
+        cp /home/$USER/.config/lxterminal/lxterminal.conf /etc/skel/.config/lxterminal/
         sleep 2
             if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                echo "#Error"
-                sleep 1
-                zenity --error --width="220" --title="  Error" \
-                       --text="\nAn error occurred while changing the Terminal theme!"
-            fi
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nChanging the Terminal theme!"
+                        fi
 }
 
 # Set lite-welcome to autostart on first boot
 # Executes at the end because the package lite-welcome needs to be installed first
 LITEWELCOME() {
-    echo "#• Setting Lite Welcome to autostart..."
-    if [ -e /home/$USER/.config/autostart/lite_welcome.desktop ]; then
-        continue
-    else
 UPDATER=$( ln -s /usr/share/applications/lite_welcome.desktop /home/$USER/.config/autostart && sleep 2 |
-zenity --progress --no-cancel --width="300" --percentage=20 --window-icon="$run_icon"  --title="Setting Lite Welcome to autostart..." --auto-close)
+zenity --progress --percentage=20  --title="Setting Lite Welcome to autostart..." \
+--width=600 --auto-close)
             if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                echo "#Error"
-                sleep 1
-                zenity --error --width="320" --title="   Error" \
-                       --text="\nAn error occurred while setting Lite Welcome to autostart on first boot! \n\n( You may already have it enabled )"
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text='There was an error while setting\nLite Welcome to autostart on first boot!\n\n(You may already have it enabled)'
              fi
 unset UPDATER
-fi
 }
 
 # Change to new HTOP theme, file is: /home/$USER/.config/htop/htoprc
 HTOPTHEME() {
-    echo "#• Updating to new Resource Usage theme..."
+    echo "#Updating to new Resource Usage theme..."
         touch /home/$USER/.config/htop/htoprc
         echo "fields=0 48 17 18 38 39 40 2 46 47 49 1" >> /home/$USER/.config/htop/htoprc
         echo "sort_key=46" >> /home/$USER/.config/htop/htoprc
@@ -139,51 +204,51 @@ HTOPTHEME() {
         echo "left_meter_modes=1 1 1" >> /home/$USER/.config/htop/htoprc
         echo "right_meters=RightCPUs2 Tasks LoadAverage Uptime" >> /home/$USER/.config/htop/htoprc
         echo "right_meter_modes=1 2 2 2" >> /home/$USER/.config/htop/htoprc
+        cp /home/$USER/.config/htop/htoprc /etc/skel/.config/htop/
         sleep 2
             if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-                echo "#Error"
-                sleep 1
-                zenity --error --width="220" --title="   Error" \
-                       --text="\nAn error occurred while changing the Terminal theme!"
-            fi
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nChanging the Terminal theme!"
+                        fi
 }
 
 REBOOT() {
-# Reboot dialog
+# Reboot dialogue 
 # Credit to xunil: http://bbs.archbang.org/viewtopic.php?id=279
-while (true); do
-# Set app icon variable
-THEME=$(xfconf-query -c xsettings -p /Net/IconThemeName)
-if [ -f "/home/$USER/.icons/${THEME}/apps/32/system-reboot.png" ]; then
-    APPICON="/home/$USER/.icons/${THEME}"
-elif [ -f "/usr/share/icons/${THEME}/apps/32/system-reboot.png" ]; then
-      APPICON="/usr/share/icons/${THEME}"
-else
-    APPICON="/usr/share/icons/Faenza"
-fi 
-
-title="Lite Upgrade Utility"
-exit_type=`zenity --width="340" --height="180" --window-icon="$ic" --title="$title" --text='                <span font="Sans Bold 10">Upgrade routine completed</span>\n' \
-                  --list --imagelist --print-column=2 --column="  " --column="Action" --column="Description" \
-    "$APPICON/apps/32/system-reboot.png" "Restart" "Reboot your computer now" \
-    "$APPICON/actions/32/system-shutdown.png" "Shutdown" "Shutdown your computer now" `
+title="Linux Lite Upgrade Complete"
+exit_type=`zenity  --width="400" --height="220" --title="$title" --list --radiolist --column="Select" \
+    --column="Exit Type" --column="Description" \
+    TRUE "Reboot" "Reboot your computer"\
+    FALSE "Shutdown" "Shutdown your computer"\
+    FALSE "Cancel" "Continue using your computer" `
 
 # User must select a target type (Check if they cancelled)
 if [ ! "$exit_type" ]; then
-    zenity --warning --timeout=6 --width="320" --title="$title - Warning" --text="\nYou should either <b>Restart</b> or <b>Shutdown</b> the system at this point. It is highly recommended to do so!"
-    continue
+    zenity --error --title="Error" --text="You must make a selection"
+    zenity --info --title="Linux Lite Upgrade Utility" --text="Upgrade complete.\n\nDon't forget to restart your computer\nto complete the upgrade."
+    exit
 fi
 
 # Action to perform by user
-if [ "$exit_type" = "Restart" ]; then
-    # Do Reboot here
+if [ "$exit_type" = "Reboot" ]
+then
+
+        # Do Reboot here
     dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Restart
 
-elif [ "$exit_type" = "Shutdown" ]; then
+elif [ "$exit_type" = "Shutdown" ]
+then
     # Do Shutdown here
     dbus-send --system --print-reply --dest="org.freedesktop.ConsoleKit" /org/freedesktop/ConsoleKit/Manager org.freedesktop.ConsoleKit.Manager.Stop
+
+else
+
+    # Do Cancel here
+    zenity --info --title="Linux Lite Upgrade Utility" --text="Upgrade complete.\n\nDon't forget to restart your computer\nto complete the upgrade."
+    exit 0
 fi
-done
 }
 
 LL30() {
@@ -204,20 +269,58 @@ esac
 # Populate arrays based on the arch
 case "$arch" in
     x86)
-    ARRAYA+=('MKDIRBUPS')
-    ARRAYA+=('BUPHOMEUSER')
+    ARRAYA+=('MKDIRBUPS30')
+    ARRAYA+=('BUPHOMEUSER30')
     ARRAYA+=('ADDCONKY')
+    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('EXEBASHSCR')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
     ARRAYA+=('HTOPTHEME')
     ;;
     amd64)
-    ARRAYA+=('MKDIRBUPS')
-    ARRAYA+=('BUPHOMEUSER')
+    ARRAYA+=('MKDIRBUPS30')
+    ARRAYA+=('BUPHOMEUSER30')
     ARRAYA+=('ADDCONKY')
+    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('EXEBASHSCR')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('LITEWELCOME')
     ARRAYA+=('HTOPTHEME')
+    ;;
+esac
+}
+
+LL32() {
+# Invoke arrays
+ARRAYA=()       # Array for LL 3.2
+
+#Check the arch
+arch=$(uname -m)
+
+case "$arch" in
+    x86)    arch="x86"  ;;
+    i?86)   arch="x86"  ;;
+    amd64)  arch="amd64"    ;;
+    x86_64) arch="amd64"    ;;
+    * ) echo "Your Arch '$arch' -> Its not supported."  ;;
+esac
+
+# Populate arrays based on the arch
+case "$arch" in
+    x86)
+    ARRAYA+=('MKDIRBUPS32')
+    ARRAYA+=('BUPHOMEUSER32')
+    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('LITEWELCOME')
+    ;;
+    amd64)
+    ARRAYA+=('MKDIRBUPS32')
+    ARRAYA+=('BUPHOMEUSER32')
+    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('EXEBASHSCR')
+    ARRAYA+=('LITEWELCOME')
     ;;
 esac
 }
@@ -237,7 +340,7 @@ if [ ${#ARRAYA[@]} -ne 0 ]; then
         do
             $line     # Execute functions one by one
             if [ $? = 1 ]; then
-                zenity --error --title="  Lite Upgrade" --text="\nAn error occurred while performing upgrades:\n\n ${line}"
+                zenity --error --title="Lite Upgrade" --text="There was an error while performing upgrades:\n ${line}"
                 exit 1
             fi    
         let i++
@@ -249,55 +352,46 @@ if [ ${#ARRAYA[@]} -ne 0 ]; then
             sleep 2
         fi
     
-    done| zenity --progress --width=300 --window-icon="$run_icon" --no-cancel --title="Lite Upgrade" --auto-kill --auto-close 
+    done| zenity --progress  --title="Lite Upgrade" --auto-kill --auto-close --width=300
 fi
 
-# elevate to run the next script with superuser privileges
-gksu -m '
-<b>Upgrade Utility requires Administrative privileges</b>
+    gksudo /usr/bin/lite-upgrade-system-series3 "$USER"      # Run the next script with superuser privileges
 
+#LLVER=$(awk '{print $3}' /etc/llver)
+if grep "Linux Lite 3.4" /etc/llver; then
 
-                Please enter your password to continue.' /usr/bin/lite-upgrade-system-series3
+    # Set lite-welcome to autostart on first boot
+    # LITEWELCOME
 
-if grep "Linux Lite 3.2" /etc/llver; then
-    # Call the reboot dialog
+    # Call the reboot dialogue
     REBOOT
+
 else
-    zenity --info --width="200" --title=" Linux Lite Upgrade Utility" --text="\nUpgrade has been canceled."
-    exit 0
+    zenity --info --title="Linux Lite Upgrade Utility" --text="Upgrade canceled."
 fi
 }
 
-# check current version and start the appropriate function
+#Check the version and start  the appropriate function
+#LLVER=$(awk '{print $3}' /etc/llver)
+
 if grep "Linux Lite 3.0" /etc/llver; then
     LL30
+elif grep "Linux Lite 3.2" /etc/llver; then
+    LL32
 else
-     zenity --info  --title="Linux Lite Upgrade Utility" --width=260 --height=60 \
-	    --text="\nYou are already running the latest release."
+
+    zenity --info --text="You are already running the latest release"
     exit 0
 fi
 
 # First dialogue box
-zenity --question --icon-name="info" --width="380" --ok-label="Upgrade Now !" --cancel-label="Cancel" --title="   Linux Lite Upgrade Utility" --window-icon="$ic" \
-        --text='\n      <span font="Sans Bold 10">You are about to upgrade to Linux Lite 3.2</span>\n\n \
-- Your computer must be (and stay) connected to the Internet during the upgrade.\n \
-- A connectivity check to Linux Lite repositories will be conducted to ensure connection can be established with the server.\n \
-- Once upgrades have taken place, you must restart the system to complete the upgrade process.\n \
-Please save your work or click <b>Cancel</b> to exit now; <b>Upgrade</b> to proceed.\n'
+zenity --question --title="Linux Lite Upgrade Utility" --window-icon="/usr/share/icons/zenity-llcc.png" \
+--text="We will now Upgrade your system to Linux Lite 3.4\n\nPlease ensure you are connected to the internet before you start.\n\nAt the end of this upgrade, please reboot to complete the upgrade process.\n\nClick Yes to continue or No to abort."
 
-# cancel 
+# If No is clicked then exit
 if [ "${PIPESTATUS[0]}" -ne "0" ]; then
-    zenity --info --width="190" --title=" Linux Lite Upgrade Utility" --text="\nUpgrade has been canceled."
-    exit 0
-fi
-
-# Check Internet access
-if eval "curl -sk http://repo.linuxliteos.com" >> /dev/null 2>&1; then
-    :  # continue - internet connection check passed 
-else # Prompt ERROR internet connection check failed and exit
-    zenity --error --width=320 --height=120 --title="  Upgrade Utility - No Internet connection..." \
-           --text="Upgrade Utility was unable to communicate with Linux Lite repositoy server.\n\nPlease check your Internet connection and try again."
-    exit 0
+    zenity --info --title='Linux Lite Upgrade Utility' --text='Upgrade cancelled.' --width="250"
+      exit 0
 fi
 
 RUN
