tidy up, create htop theme in /etc/skel for new users

diff --git a/usr/bin/lite-upgrade-system-series3 b/usr/bin/lite-upgrade-system-series3
--- a/usr/bin/lite-upgrade-system-series3
+++ b/usr/bin/lite-upgrade-system-series3
@@ -59,6 +59,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('HTOPSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('GETCONKY')
     ARRAYC+=('UPDCONKSKEL')
@@ -72,6 +73,7 @@ case "$arch" in
     ARRAYC+=('UPLSBISSUE')
     ARRAYC+=('UPGRUB')
     ARRAYC+=('LBPLYUB')
+    ARRAYC+=('HTOPSKEL')
     ARRAYC+=('ALLTERTHEM')
     ARRAYC+=('GETCONKY')
     ARRAYC+=('UPDCONKSKEL')
@@ -250,6 +252,43 @@ zenity --progress --no-cancel --percentage="$PERCENTAGE"  --title="Updating boot
                 zenity --info --title="Lite Upgrade" --text="Error:\n${line}"
             fi    
 unset UPDATER
+}
+
+# Change to new HTOP theme, file is: /etc/skel/.config/htop/htoprc
+HTOPSKEL() {
+    echo "#Updating to new Resource Usage theme..."
+        touch /etc/skel/.config/htop/htoprc
+        echo "fields=0 48 17 18 38 39 40 2 46 47 49 1" >> /etc/skel/.config/htop/htoprc
+        echo "sort_key=46" >> /etc/skel/.config/htop/htoprc
+        echo "sort_direction=1" >> /etc/skel/.config/htop/htoprc
+        echo "hide_threads=0" >> /etc/skel/.config/htop/htoprc
+        echo "hide_kernel_threads=1" >> /etc/skel/.config/htop/htoprc
+        echo "hide_userland_threads=0" >> /etc/skel/.config/htop/htoprc
+        echo "shadow_other_users=0" >> /etc/skel/.config/htop/htoprc
+        echo "show_thread_names=0" >> /etc/skel/.config/htop/htoprc
+        echo "show_program_path=1" >> /etc/skel/.config/htop/htoprc
+        echo "highlight_base_name=0" >> /etc/skel/.config/htop/htoprc
+        echo "highlight_megabytes=1" >> /etc/skel/.config/htop/htoprc
+        echo "highlight_threads=1" >> /etc/skel/.config/htop/htoprc
+        echo "tree_view=0" >> /etc/skel/.config/htop/htoprc
+        echo "header_margin=1" >> /etc/skel/.config/htop/htoprc
+        echo "detailed_cpu_time=0" >> /etc/skel/.config/htop/htoprc
+        echo "cpu_count_from_zero=0" >> /etc/skel/.config/htop/htoprc
+        echo "update_process_names=0" >> /etc/skel/.config/htop/htoprc
+        echo "account_guest_in_cpu_meter=0" >> /etc/skel/.config/htop/htoprc
+        echo "color_scheme=5" >> /etc/skel/.config/htop/htoprc
+        echo "delay=15" >> /etc/skel/.config/htop/htoprc
+        echo "left_meters=LeftCPUs2 Memory Swap" >> /etc/skel/.config/htop/htoprc
+        echo "left_meter_modes=1 1 1" >> /etc/skel/.config/htop/htoprc
+        echo "right_meters=RightCPUs2 Tasks LoadAverage Uptime" >> /etc/skel/.config/htop/htoprc
+        echo "right_meter_modes=1 2 2 2" >> /etc/skel/.config/htop/htoprc
+        sleep 2
+            if [ "${PIPESTATUS[0]}" -ne "0" ]; then
+                        echo "#Error"
+                    sleep 2
+                                        zenity --error \
+                                        --title="Error" --text="There was an error while\nChanging the Resource Usage theme!"
+                        fi
 }
 
 # Modify Terminal theme in /etc/skel
