more descriptive titles, clean up, rearrangement & fixes

diff --git a/usr/bin/lite-upgrade-series3 b/usr/bin/lite-upgrade-series3
--- a/usr/bin/lite-upgrade-series3
+++ b/usr/bin/lite-upgrade-series3
@@ -114,24 +114,24 @@ BUPHOMEUSER34() {
 }
 
 # Add Lite Desktop Widget
-ADDCONKY() {
-  log_upgrade "ADDCONKY"
+ADDLITEWIDG() {
+  log_upgrade "ADDLITEWIDG"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(cd /home/"'$MYUSER'" && wget http://repo.linuxliteos.com/upgrade/3.0-3.2/liteconkywidget.tar.gz && tar xvzf liteconkywidget.tar.gz && rm liteconkywidget.tar.gz && sleep 2 )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=400 --percentage="$PERCENTAGE" --title="$APPNAME" --auto-close --no-cancel --text="Adding Lite Desktop Widget...")
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "ADDCONKY - Error"
+  zenity --progress --width=400 --percentage="$PERCENTAGE" --title="Adding Lite Desktop Widget..." --auto-close --no-cancel --text=" ")
+  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "ADDLITEWIDG - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --title="Error" --text="An error occurred while adding the Lite Desktop Widget.\n\n$REPORTERROR"
   fi
 unset UPDATER
 }
 
 # Improvements to the Lite Desktop Widget
-UPDCONKY() {
-  log_upgrade "UPDCONKY"
+UPDLITEWIDG() {
+  log_upgrade "UPDLITEWIDG"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(sed -i "s/Logged in as.*/${color}Logged in as:   \${alignr}\${color}\$USER"/g /home/"'$MYUSER'"/.conky/widget && sleep 2 )' 2>&1 |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=400 --percentage="$PERCENTAGE" --title="$APPNAME" --auto-close --no-cancel --text="Updating the Lite Desktop Widget...")
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "UPDCONKY - Error"
+  zenity --progress --width=400 --percentage="$PERCENTAGE" --title="Updating the Lite Desktop Widget..." --auto-close --no-cancel --text=" ")
+  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "UPDLITEWIDG - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --title="Error" --text="An error occurred while updating the Lite Desktop Widget.\n\n$REPORTERROR"
   fi
 unset UPDATER
@@ -159,8 +159,6 @@ EXEBASHSCR() {
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while adding the Execute bash scripts feature.\n\n$REPORTERROR"
   fi
   unset BASHSEXECDEFAULT
-#UPDATER=$( stdbuf -oL /bin/bash \-c '( sudo -u '${MYUSER}' xfconf-query --channel thunar --property /misc-exec-shell-scripts-by-default --create --type bool --set true && sleep 2 )' 2>&1 |
-#stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
   if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "EXEBASHSCR - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while adding the Execute bash scripts feature.\n\n$REPORTERROR"
   fi
@@ -168,20 +166,20 @@ EXEBASHSCR() {
 }
 
 # Change Notification theme
-NOTIFYCH() {
-  log_upgrade "NOTIFYCH"
+NOTIFYTHM() {
+  log_upgrade "NOTIFYTHM"
   echo "#⚫ Updating to new Notification theme..."
   cp /home/$MYUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml /home/$MYUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml.backup 2>&1 | tee -a $LOGFILE
   sed -i '5d' /home/$MYUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml 2>&1 | tee -a $LOGFILE
   sed -i '5i\ \ <property name="theme" type="string" value="Default"/>' /home/$MYUSER/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml 2>&1 | tee -a $LOGFILE
-  sleep 2 ; if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "NOTIFYCH - Error"
+  sleep 2 ; if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "NOTIFYTHM - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while changing the Notification theme.\n\n$REPORTERROR"
   fi
 }
 
 # Window snapping & tiling
-WINSNAP() {
-  log_upgrade "WINSNAP"
+WINSNAPTILE() {
+  log_upgrade "WINSNAPTILE"
   XFWM4=".config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml"
   ( sed -i 's/.*snap_resist.*/    <property name="snap_resist" type="bool" value="true"\/>/' /etc/skel/$XFWM4 2>&1 | tee -a $LOGFILE
   sed -i 's/.*tile_on_move.*/    <property name="tile_on_move" type="bool" value="true"\/>/' /etc/skel/$XFWM4 2>&1 | tee -a $LOGFILE
@@ -190,7 +188,7 @@ WINSNAP() {
   sed -i 's/.*tile_on_move.*/    <property name="tile_on_move" type="bool" value="true"\/>/' /home/$MYUSER/$XFWM4 2>&1 | tee -a $LOGFILE
   sed -i 's/.*wrap_windows.*/    <property name="wrap_windows" type="bool" value="false"\/>/' /home/$MYUSER/$XFWM4 2>&1 | tee -a $LOGFILE && sleep 2 |
   zenity --progress --width=400 --title="$APPNAME" --percentage=20  --auto-close --no-cancel --text="Setting Window snapping feature...")
-  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "WINSNAP - Error"
+  if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "WINSNAPTILE - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while setting the Window snapping feature.\n\n$REPORTERROR"
   fi
 unset XFWM4
@@ -224,27 +222,7 @@ TERMTHEME() {
   fi
 }
 
-# Bluray additional support in VLC - USER
-BLURAYVLCUSER() {
-  log_upgrade "BLURAYVLCUSER"
-  echo "#⚫ Adding additional Bluray support in VLC for users..."
-   mkdir -p /home/$MYUSER/.config/aacs ; cd /home/$MYUSER/.config/aacs/ ; wget http://repo.linuxliteos.com/upgrade/3.0-3.6/KEYDB.cfg ; chown -R $MYUSER:$MYUSER /home/$MYUSER/.config/aacs 2>&1 | tee -a $LOGFILE
-  sleep 2 ; if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "BLURAYVLCUSER - Error"
-    zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while adding additional Bluray support in VLC for users.\n\n$REPORTERROR"
-  fi
-}
-
-# Set lite-welcome to autostart on first boot
-LITEWELCOME() {
-  log_upgrade "LITEWELCOME"
-  echo "#⚫ Setting Lite Welcome to autostart..." && sleep 2
-  if [ ! -f /home/$MYUSER/.config/autostart/lite_welcome.desktop ]; then
-  UPDATER=$( ln -s /usr/share/applications/lite_welcome.desktop /home/$MYUSER/.config/autostart 2>&1 | tee -a $LOGFILE )
-  else :; fi
-unset UPDATER
-}
-
-# Change to new HTOP theme, file is: /home/$MYUSER/.config/htop/htoprc
+# Change to new HTOP/Resource Usage theme, file is: /home/$MYUSER/.config/htop/htoprc
 HTOPTHEME() {
   log_upgrade "HTOPTHEME"
   echo "#⚫ Updating to new Resource Usage theme..."
@@ -276,6 +254,26 @@ HTOPTHEME() {
   sleep 2 ; if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2; log_upgrade "HTOPTHEME - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while changing the Resource Usage theme.\n\n$REPORTERROR"
   fi
+}
+
+# Bluray additional support in VLC - USER
+BLURAYVLCUSER() {
+  log_upgrade "BLURAYVLCUSER"
+  echo "#⚫ Adding additional Bluray support in VLC for users..."
+   mkdir -p /home/$MYUSER/.config/aacs ; cd /home/$MYUSER/.config/aacs/ ; wget http://repo.linuxliteos.com/upgrade/3.0-3.6/KEYDB.cfg ; chown -R $MYUSER:$MYUSER /home/$MYUSER/.config/aacs 2>&1 | tee -a $LOGFILE
+  sleep 2 ; if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2 ; log_upgrade "BLURAYVLCUSER - Error"
+    zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while adding additional Bluray support in VLC for users.\n\n$REPORTERROR"
+  fi
+}
+
+# Set lite-welcome to autostart on first boot
+LITEWELCOME() {
+  log_upgrade "LITEWELCOME"
+  echo "#⚫ Setting Lite Welcome to autostart..." && sleep 2
+  if [ ! -f /home/$MYUSER/.config/autostart/lite_welcome.desktop ]; then
+  UPDATER=$( ln -s /usr/share/applications/lite_welcome.desktop /home/$MYUSER/.config/autostart 2>&1 | tee -a $LOGFILE )
+  else :; fi
+unset UPDATER
 }
 
 REBOOT() {
@@ -327,26 +325,26 @@ case "$arch" in
     x86)
     ARRAYA+=('MKDIRBUPS30')
     ARRAYA+=('BUPHOMEUSER30')
-    ARRAYA+=('ADDCONKY')
+    ARRAYA+=('ADDLITEWIDG')
     ARRAYA+=('EXEBASHSCR')
-    ARRAYA+=('NOTIFYCH')
-    ARRAYA+=('WINSNAP')
+    ARRAYA+=('NOTIFYTHM')
+    ARRAYA+=('WINSNAPTILE')
     ARRAYA+=('TERMTHEME')
+    ARRAYA+=('HTOPTHEME')
     ARRAYA+=('BLURAYVLCUSER')
     ARRAYA+=('LITEWELCOME')
-    ARRAYA+=('HTOPTHEME')
     ;;
     amd64)
     ARRAYA+=('MKDIRBUPS30')
     ARRAYA+=('BUPHOMEUSER30')
-    ARRAYA+=('ADDCONKY')
+    ARRAYA+=('ADDLITEWIDG')
     ARRAYA+=('EXEBASHSCR')
-    ARRAYA+=('NOTIFYCH')
-    ARRAYA+=('WINSNAP')
+    ARRAYA+=('NOTIFYTHM')
+    ARRAYA+=('WINSNAPTILE')
     ARRAYA+=('TERMTHEME')
+    ARRAYA+=('HTOPTHEME')
     ARRAYA+=('BLURAYVLCUSER')
     ARRAYA+=('LITEWELCOME')
-    ARRAYA+=('HTOPTHEME')
     ;;
 esac
 }
@@ -372,10 +370,10 @@ case "$arch" in
     x86)
     ARRAYA+=('MKDIRBUPS32')
     ARRAYA+=('BUPHOMEUSER32')
-    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('UPDLITEWIDG')
     ARRAYA+=('EXEBASHSCR')
-    ARRAYA+=('NOTIFYCH')
-    ARRAYA+=('WINSNAP')
+    ARRAYA+=('NOTIFYTHM')
+    ARRAYA+=('WINSNAPTILE')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('BLURAYVLCUSER')
     ARRAYA+=('LITEWELCOME')
@@ -383,10 +381,10 @@ case "$arch" in
     amd64)
     ARRAYA+=('MKDIRBUPS32')
     ARRAYA+=('BUPHOMEUSER32')
-    ARRAYA+=('UPDCONKY')
+    ARRAYA+=('UPDLITEWIDG')
     ARRAYA+=('EXEBASHSCR')
-    ARRAYA+=('NOTIFYCH')
-    ARRAYA+=('WINSNAP')
+    ARRAYA+=('NOTIFYTHM')
+    ARRAYA+=('WINSNAPTILE')
     ARRAYA+=('TERMTHEME')
     ARRAYA+=('BLURAYVLCUSER')
     ARRAYA+=('LITEWELCOME')
diff --git a/usr/bin/lite-upgrade-system-series3 b/usr/bin/lite-upgrade-system-series3
--- a/usr/bin/lite-upgrade-system-series3
+++ b/usr/bin/lite-upgrade-system-series3
@@ -1,6 +1,6 @@
 #!/bin/bash
 #----------------------------------------------------------------
-# Description: Linux Lite Upgrade Script - Home
+# Description: Linux Lite Upgrade Script - System
 # About: For Linux Lite 3.- Series only
 # Licence: GPLv2 Sharing is Caring
 # Author: Jerry Bezencon, Ralphy
@@ -38,37 +38,37 @@ esac
 case "$arch" in
     x86)
     ARRAYB+=('BUPETCSKEL30')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
-    ARRAYC+=('NOTIFYCHSKEL')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
+    ARRAYC+=('NOTIFYTHMSKEL')
     ARRAYC+=('HTOPSKEL')
-    ARRAYC+=('ALLTERTHEM')
+    ARRAYC+=('ALLTERTHEME')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
-    ARRAYC+=('GETCONKY')
-    ARRAYC+=('UPDCONKSKEL')
+    ARRAYC+=('ADDLITEWIDGSKEL')
+    ARRAYC+=('UPDLITEWIDGSKEL')
     ;;
     amd64)
     ARRAYB+=('BUPETCSKEL3064')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL64')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
-    ARRAYC+=('NOTIFYCHSKEL')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
+    ARRAYC+=('NOTIFYTHMSKEL')
     ARRAYC+=('HTOPSKEL')
-    ARRAYC+=('ALLTERTHEM')
+    ARRAYC+=('ALLTERTHEME')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
-    ARRAYC+=('GETCONKY')
-    ARRAYC+=('UPDCONKSKEL')
+    ARRAYC+=('ADDLITEWIDGSKEL')
+    ARRAYC+=('UPDLITEWIDGSKEL')
     ;;
 esac
 }
@@ -93,33 +93,33 @@ esac
 case "$arch" in
     x86)
     ARRAYB+=('BUPETCSKEL32')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
-    ARRAYC+=('NOTIFYCHSKEL')
-    ARRAYC+=('ALLTERTHEM')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
+    ARRAYC+=('NOTIFYTHMSKEL')
+    ARRAYC+=('ALLTERTHEME')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
-    ARRAYC+=('UPDCONKSKEL')
+    ARRAYC+=('UPDLITEWIDGSKEL')
     ;;
     amd64)
     ARRAYB+=('BUPETCSKEL3264')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL64')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
-    ARRAYC+=('NOTIFYCHSKEL')
-    ARRAYC+=('ALLTERTHEM')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
+    ARRAYC+=('NOTIFYTHMSKEL')
+    ARRAYC+=('ALLTERTHEME')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
-    ARRAYC+=('UPDCONKSKEL')
+    ARRAYC+=('UPDLITEWIDGSKEL')
     ;;
 esac
 }
@@ -144,25 +144,25 @@ esac
 case "$arch" in
     x86)
     ARRAYB+=('BUPETCSKEL34')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
     ;;
     amd64)
     ARRAYB+=('BUPETCSKEL3464')
-    ARRAYC+=('UPD1')
-    ARRAYC+=('ERASEDPKG')
+    ARRAYC+=('UPDPKGS')
+    ARRAYC+=('ERASEDPKGS')
     ARRAYC+=('INPKCL64')
-    ARRAYC+=('ADDWALL1')
+    ARRAYC+=('ADDWALLS')
     ARRAYC+=('UPLSBISSUE')
-    ARRAYC+=('UPGRUB')
-    ARRAYC+=('LBPLYUB')
+    ARRAYC+=('UPDGRUB')
+    ARRAYC+=('UPDPLYM')
     ARRAYC+=('BLURAYVLCSYS')
     ARRAYC+=('ARCTHEMETHUNDERB')
     ;;
@@ -221,19 +221,19 @@ BUPETCSKEL3464() {
 }
 
 # Get list of available updated packages
-UPD1() {
-  log_upgrade "UPD1"
+UPDPKGS() {
+  log_upgrade "UPDPKGS"
   UPDATER=$( stdbuf -oL /bin/bash \-c '( apt-get update \-y )' 2>&1 | tee -a $LOGFILE | stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="$APPNAME" --text="Updating package information...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Updating repositories..." --text="Updating repositories...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 }
 
 # Erase existing available info
-ERASEDPKG() {
-  log_upgrade "ERASEDPKG"
+ERASEDPKGS() {
+  log_upgrade "ERASEDPKGS"
   UPDATER=$( stdbuf -oL /bin/bash \-c '( dpkg --clear-avail )' 2>&1 | tee -a $LOGFILE | stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="$APPNAME" --text="Clearing dpkg...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Clearing dpkg..." --text="Clearing dpkg...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 }
@@ -243,7 +243,7 @@ INPKCL() {
   log_upgrade "INPKCL"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \-y && apt-get install libreoffice-gnome linux-generic conky-all xserver-xorg-input-joystick joystick yad lite-updatesnotify bcmwl-kernel-source xclip libaacs0 libbluray-bdj libbluray1 \-y && echo flashplugin-installer flashplugin-installer/local string | debconf-set-selections && apt-get install flashplugin-installer \-y && apt-get update \-y && apt-get remove adobe-flashplugin \-y && apt-get autoremove \-y && apt-get clean )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="$APPNAME" --text="Downloading and Installing new packages...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Downloading and Installing new packages..." --text="Downloading and Installing new packages...")
 unset UPDATER
 }
 
@@ -252,13 +252,13 @@ INPKCL64() {
   log_upgrade "INPKCL64"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \-y && apt-get install libreoffice-gnome linux-generic conky-all xserver-xorg-input-joystick joystick yad lite-updatesnotify bcmwl-kernel-source xclip libaacs0 libbluray-bdj libbluray1 \-y && echo flashplugin-installer flashplugin-installer/local string | debconf-set-selections && apt-get install flashplugin-installer \-y && apt-get update \-y && apt-get remove adobe-flashplugin \-y && apt-get autoremove \-y && apt-get clean )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="$APPNAME" --text="Downloading and Installing new packages...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Downloading and Installing new packages..." --text="Downloading and Installing new packages...")
 unset UPDATER
 }
 
 # Add new wallpapers
-ADDWALL1() {
-  log_upgrade "ADDWALL1"
+ADDWALLS() {
+  log_upgrade "ADDWALLS"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(cd /tmp && wget http://repo.linuxliteos.com/upgrade/3.0-3.6/walls36.tar.gz &&  tar -xvf walls36.tar.gz -C /usr/share/backgrounds/xfce/ && cd /usr/share/backgrounds/xfce/ && chown root:root * && chmod 644 * && sleep 2 )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Adding new wallpapers...")
 unset UPDATER
@@ -267,24 +267,24 @@ unset UPDATER
 # Update lsb_release and issue files /etc changes, update /etc/llver
 UPLSBISSUE() {
   log_upgrade "UPLSBISSUE"
-  UPDATER=$( stdbuf -oL /bin/bash \-c '( sed -i "s/DISTRIB_DESCRIPTION=.*/DISTRIB_DESCRIPTION=\"Linux Lite "'$UPGR'"\"/g" /etc/lsb-release && echo "Linux Lite $UPGR" | tee /etc/llver && echo "Linux Lite $UPGR LTS \n \l" | tee /etc/issue && sleep 2 )' 2>&1 | tee -a $LOGFILE | stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
+  UPDATER=$( stdbuf -oL /bin/bash \-c '( sed -i "s/DISTRIB_DESCRIPTION=.*/DISTRIB_DESCRIPTION=\"Linux Lite "'$UPGR'"\"/g" /etc/lsb-release && echo "Linux Lite $UPGR LTS \n \l" | tee /etc/issue && echo "Linux Lite $UPGR" | tee /etc/llver && sleep 2 )' 2>&1 | tee -a $LOGFILE | stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
   zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Updating version information...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 }
 
 # Update grub
-UPGRUB() {
-  log_upgrade "UPGRUB"
+UPDGRUB() {
+  log_upgrade "UPDGRUB"
   UPDATER=$( stdbuf -oL /bin/bash \-c '( update-grub && sleep 2 )' 2>&1 | tee -a $LOGFILE | stdbuf -oL sed -n -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="$APPNAME" --text="Updating grub...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Updating Grub..." --text="Updating Grub...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 }
 
-# /lib/plymouth/themes/ubuntu-text/ changes
-LBPLYUB() {
-  log_upgrade "LBPLYUB"
+# Update /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
+UPDPLYM() {
+  log_upgrade "UPDPLYM"
   UPDATER=$( stdbuf -oL /bin/bash \-c '( sed -i "s/^title=Linux Lite.*$/title=Linux Lite "'$UPGR'"/g" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth ;
   sed -i "s/^title=Ubuntu.*$/title=Linux Lite "'$UPGR'"/g" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth ;
   sed -i "s/black=0x2c001e/black=0x000000/g" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth ;
@@ -292,19 +292,19 @@ LBPLYUB() {
   sed -i "s/brown=0xff4012/brown=0xffff00/g" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth ;
   sed -i "s/blue=0x988592/blue=0x000000/g" /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth && update-initramfs -u && sleep 2 )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Updating boot configuration please wait...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Updating boot configuration please wait...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 }
 
 # Change Notification theme
-NOTIFYCHSKEL() {
-  log_upgrade "NOTIFYCHSKEL"
+NOTIFYTHMSKEL() {
+  log_upgrade "NOTIFYTHMSKEL"
   echo "#⚫ Updating to new Notification theme..."
   cp /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml.backup 2>&1 | tee -a $LOGFILE
   sed -i '5d' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml 2>&1 | tee -a $LOGFILE
   sed -i '5i\ \ <property name="theme" type="string" value="Default"/>' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-notifyd.xml 2>&1 | tee -a $LOGFILE
-  sleep 2 && if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2; log_upgrade "NOTIFYCHSKEL - Error"
+  sleep 2 && if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2; log_upgrade "NOTIFYTHMSKEL - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while changing the Notification theme.\n\n$REPORTERROR"
   fi
 }
@@ -344,9 +344,9 @@ HTOPSKEL() {
 }
 
 # Modify Terminal theme in /etc/skel
-ALLTERTHEM() {
-  log_upgrade "ALLTERTHEM"
-  echo "#Updating system Terminal themes..."
+ALLTERTHEME() {
+  log_upgrade "ALLTERTHEME"
+  echo "#⚫ Updating system Terminal themes..."
   mv /etc/skel/.config/lxterminal/lxterminal.conf /etc/skel/.config/lxterminal/lxterminal.conf.backup 2>&1 | tee -a $LOGFILE
   touch /etc/skel/.config/lxterminal/lxterminal.conf 2>&1 | tee -a $LOGFILE
   echo "[general]" >> /etc/skel/.config/lxterminal/lxterminal.conf 2>&1 | tee -a $LOGFILE
@@ -369,7 +369,7 @@ ALLTERTHEM() {
   mv /root/.config/lxterminal/lxterminal.conf /root/.config/lxterminal/lxterminal.conf.backup 2>&1 | tee -a $LOGFILE
   cp /etc/skel/.config/lxterminal/lxterminal.conf /root/.config/lxterminal/ 2>&1 | tee -a $LOGFILE
   chown root:root /root/.config/lxterminal/lxterminal.conf 2>&1 | tee -a $LOGFILE
-  sleep 2 && if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2; log_upgrade "ALLTERTHEM - Error"
+  sleep 2 && if [ "${PIPESTATUS[0]}" -ne "0" ]; then echo "#✘ Error..." && sleep 2; log_upgrade "ALLTERTHEME - Error"
     zenity --error --width="340" --title="$APPNAME - Error" --text="An error occurred while changing the system Terminal themes.\n\n$REPORTERROR"
   fi
 }
@@ -378,7 +378,7 @@ ALLTERTHEM() {
 BLURAYVLCSYS() {
   log_upgrade "BLURAYVLCSYS"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(mkdir -p /etc/skel/.config/aacs && cd /etc/skel/.config/aacs/ && wget http://repo.linuxliteos.com/upgrade/3.0-3.6/KEYDB.cfg && sleep 2 )' 2>&1 | tee -a $LOGFILE |
-  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' | zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="$APPNAME" --text="Adding additional Bluray support in VLC for the system...")
+  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' | zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Adding additional Bluray support for VLC in skel...")
 unset UPDATER
 }
 
@@ -387,24 +387,24 @@ unset UPDATER
 ARCTHEMETHUNDERB() {
   log_upgrade "ARCTHEMETHUNDERB"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(wget -O /usr/local/sbin/mozilla-extension-manager http://repo.linuxliteos.com/upgrade/3.0-3.6/mozilla-extension-manager && chmod +x /usr/local/sbin/mozilla-extension-manager && mozilla-extension-manager --system --thunderbird --install http://repo.linuxliteos.com/upgrade/3.0-3.6/arcthunderbird.xpi && sleep 2 )' 2>&1 | tee -a $LOGFILE |
-  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="Adding Arc theme to Thunderbird...")
+  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Adding Arc theme to Thunderbird globally...")
 unset UPDATER
 }
 
 # Get Conky for Linux Lite 3.0 add it to /etc/skel
-GETCONKY() {
-  log_upgrade "GETCONKY"
+ADDLITEWIDGSKEL() {
+  log_upgrade "ADDLITEWIDGSKEL"
   UPDATER=$( stdbuf -oL /bin/bash \-c '(cd /etc/skel && wget http://repo.linuxliteos.com/upgrade/3.0-3.2/liteconkywidget.tar.gz && tar xvzf liteconkywidget.tar.gz && rm liteconkywidget.tar.gz &&  chown root:root .conky && sleep 2 )' 2>&1 | tee -a $LOGFILE |
-  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' | zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE"  --title="$APPNAME" --text="Adding Lite Widget to /etc/skel...")
+  stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' | zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Adding Lite Widget into skel...")
 unset UPDATER
 }
 
 # Improvements to the Lite Desktop Widget
-UPDCONKSKEL() {
-  log_upgrade "UPDCONKSKEL"
+UPDLITEWIDGSKEL() {
+  log_upgrade "UPDLITEWIDGSKEL"
   UPDATER=$( stdbuf -oL /bin/bash \-c '( sed -i "s/Logged in as.*/${color}Logged in as:   \${alignr}\${color}\$USER"/g /etc/skel/.conky/widget && sleep 2 )' 2>&1 | tee -a $LOGFILE |
   stdbuf -oL sed -n -e 's/^\(.\{128\}\).*/\1/' -e '/\[*$/ s/^/# /p' -e '/\*$/ s/^/# /p' |
-  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="$APPNAME" --text="Updating the Lite Desktop Widget in skel...")
+  zenity --progress --width=600 --auto-close --no-cancel --percentage="$PERCENTAGE" --title="Updating the Lite Desktop Widget in skel...")
   if [ $? = 1 ]; then zenity --info --title="$APPNAME" --text="\nError:\n${line}"; fi
 unset UPDATER
 return
